### ISSUE TITLE
additionnal counter?

### ISSUE THREAD

**Issue by Lepterois** [mattogodoy/open-trip#1]
Hi! great project!
I'm going to make one for my bike!
Do you think, is it possible to add an rpm counter for the engine?
Thanks to reply!

**Comment by mattogodoy** [comment]
Hi! 
Sure, it is possible, but for that you should have a way to measure every revolution. Most people makes it using the spark plug as a way to count. For instance: https://kokoraskostas.blogspot.com.es/2013/12/arduino-inductive-spark-plug-sensor.html

Good luck!

**Comment by Lepterois** [comment]
Thanks for the reply!
Is it possible to use the original wires of the rpm meter?

**Comment by mattogodoy** [comment]
Well, that might be possible but I am not sure how to do it. Maybe every bike brand has a different signal for that, or is it universal?
Sorry, I don't know :)

**Comment by Lepterois** [comment]
I don't know at all. I'm completely newbie ;-)
What I know, normally it's a pulse from the engine sensor, but I think the voltage may varies from the different models of bikes?
