### ISSUE TITLE
Error with library  "PushButton.h"

### ISSUE THREAD

**Issue by inopya** [mattogodoy/open-trip#3]
I can not find the library "PushButton.h" anywhere and I can not compile ...
If I have found "Pushbutton.h" with the 'b' lowercase, but that does not contain the methods that are then called in the use of declared objects.
Could you indicate where you downloaded it from?
Thank you.

**Comment by mattogodoy** [comment]
Hi!
The correct library is called "r89m PushButton".

Try installing that one and let me know if it worked for you.

**Comment by inopya** [comment]
Thanks, that was the problem, the library

**Comment by mattogodoy** [comment]
Great! 💪

Closing the issue.
