### ISSUE TITLE
Compensacion de inclinacion

### ISSUE THREAD

**Issue by Thomas6500** [mattogodoy/open-trip#4]
Hola 

comp solventaste la inclinacion del magnetometro para tener un rumbo correcto? 
estoy implementando una brujula con rumbo para 4x4 , pero afecta la inclinación del vehículo. 
gracias

**Comment by mattogodoy** [comment]
Buenas!
No he compensado inclinación, pero sí lo he hecho con la declinación magnética.
Aquí puedes ver la parte del código que controla la brújula: https://github.com/mattogodoy/open-trip/blob/master/open-trip.ino#L411-L442

Se me ocurre que para hacer eso podrías añadir un acelerómetro que siempre sepa donde es "hacia abajo" y en función de eso compensas. Saludos!
